version: "2"

services:
  green:
    container_name: green
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080

  blue:
    container_name: blue
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8080
