version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/backend
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/backend
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: run_new_was.sh
      timeout: 120
      runas: ubuntu
