server:
  port: 9999

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/scheme.sql
      data-locations: classpath:sql/data.sql
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 63
